# [general]
# import = [
#     "~/.config/alacritty/themes/themes/vscode.toml"
# ]

[window]
padding = { x = 4, y = 4 }
decorations = "Full"
opacity = 0.9

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 10

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
        { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
        { key = "Q", mods = "Control|Shift", action = "Quit" }
]
