[general]
import = [
    "~/.config/alacritty/themes/themes/vscode.toml"
]

[window]
padding = { x = 4, y = 4 }
decorations = "Full"
opacity = 0.9

[font]
normal = { family = "Maple Mono NF CN", style = "Regular" }
size = 12

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
        { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
        { key = "Q", mods = "Control|Shift", action = "Quit" }
]
